#define GPIO_LED_BUILTIN 2
#define GPIO_SENSOR_NIVEL 5

bool ESTADO_SENSOR_NIVEL;

void setup() {
  pinMode(GPIO_LED_BUILTIN, OUTPUT);
  pinMode(GPIO_SENSOR_NIVEL, INPUT_PULLUP);
}

void loop()
{
  ESTADO_SENSOR_NIVEL = digitalRead(GPIO_SENSOR_NIVEL);
  digitalWrite(GPIO_LED_BUILTIN, ESTADO_SENSOR_NIVEL);
}
